import { Locale } from "@types";

const ukrainian = [
  [
    "А, юний шукач пригод! Моє старе серце радіє, коли бачу, що така відважна душа, як ти, наважується на небезпеки, що підстерігають нас за стінами нашого села",
    "За часів моєї молодості я теж блукав цими землями, шукаючи пригод і багатства",
    "Але досить про мене! Ти, мій друже, стоїш на порозі величі. Дозволь мені передати тобі трохи мудрості",
    "У твоїй майбутній подорожі на тебе чекає небезпека на кожному кроці. Чудовиська причаїлися в тіні, чекаючи, щоб завдати удару",
    "Меч у твоєму боці... це більше, ніж просто зброя. Це символ твоєї мужності, твоєї рішучості",
    "Пам'ятай, коли ти стикаєшся з небезпекою, не соромся володіти ним. Впевнено натискай на пробіл, і ти переможеш",
    "Але сам по собі меч не гарантує вам безпеку. Ні, тобі знадобиться щось більше",
    "Погляньте на цей щит! Створений найкращим ковалем королівства, він відверне навіть найсмертоносніші удари.",
    "Щоб скористатися його захисними обіймами, просто натисніть і утримуйте клавішу shift. З ним ви станете неприступним бастіоном захисту",
    "А тепер, юний воїне, уважно вислухай благання зневіреного батька. Мій син, викрадений підлими лиходіями, нудиться в підземеллі на заході",
    "Благаю вас, врятуйте його від викрадачів! Поверніть його мені цілим і неушкодженим, і ви будете щедро винагороджені",
    "Золотом і коштовностями? Звичайно! Але що важливіше, ти заслужиш вдячність батька, чиє серце болить від тривоги.",
    "Вперед, відважний шукачу пригод! Твоя доля чекає, а доля мого сина висить на волосині",
    "О, і перш ніж ти зайдеш надто далеко, дозволь мені згадати про цікавий намет на краю села.",
    "У ньому живе своєрідний жаб-торговець. Він торгує сильнодіючими цілющими зіллями, звареними з есенції рідкісних трав",
    "Ці еліксири здатні залікувати навіть найтяжчі рани, але за них треба платити. Його валютою є золоті монети, зібрані з бездиханного лушпиння переможених тобою монстрів",
    "Якщо ти відчуваєте гостру потребу в зціленні, відвідайте його. Його товари можуть врятувати тобі життя",
  ],
  [
    "А, так швидко повернувся? Здається, випробування підземелля не злякали твій дух",
    "Але будь обережним, мій друже. Чим глибше ти занурюєшся в темряву, тим більші випробування чекають на тебе",
    "Не дозволяй самовдоволенню стати твоєю погибеллю. Пам'ятай уроки, які я тобі дав",
    "Твій меч, твій щит... це твої інструменти, твої супутники в боротьбі зі злом",
    "І не забувайте в запалі бою про важливість стратегії. Вчасно нанесений удар, вдало поставлений блок... це може переломити хід подій на вашу користь",
    "А тепер, вперед! Доля мого сина, а можливо, і доля нашого королівства - у твоїх руках",
    "І ще одне. Якщо вам знадобиться провізія в дорогу, не оминайте увагою намет жаб'ячого торговця.",
    "Від його цілющого зілля може залежати перемога чи поразка.",
    "Від його цілющого зілля може залежати перемога чи поразка.",
  ],
  [
    "Ти повертаєшся, втомлений і виснажений. Але не бійся, бо ти показав себе справжнім героєм",
    "Мій син в безпеці, завдяки твоїй хоробрості та майстерності.",
    "Прийми цей скромний знак моєї вдячності, нагороду, гідну твоєї доблесті.",
    "І знай, юний шукач пригод: твої подвиги будуть прославлені по всій землі.",
    "Розповідь про твою відвагу надихатиме покоління, які ще не народилися.",
    "Але не дозволяй славі та удачі притупити твою гостроту. Шлях героя ніколи по-справжньому не закінчується",
    "Завжди є нові виклики, які потрібно долати, нове зло, яке потрібно перемагати",
    "Пам'ятайте уроки, які ви засвоїли, друзів, яких ви знайшли, і жертви, на які ви пішли",
    "Бо в анналах історії твоє ім'я буде вписане золотими літерами",
    "Прощавай, хоробра душе. Нехай твої пригоди будуть численними, а твоє серце завжди буде твердим",
    "І якщо тобі коли-небудь знадобиться поповнення запасів, не забувай про намет жаб'ячого торговця. Його зілля, як і раніше, сильні, як ніколи, і готові допомогти тобі у твоїх пошуках",
  ],
];
const english = [
  [
    "Ah, young adventurer! It gladdens my old heart to see a brave soul like yourself venturing into the dangers that lie beyond our village walls.",
    "In the days of my youth, I too roamed these lands, seeking adventure and fortune.",
    "But enough about me! You, my friend, stand on the precipice of greatness. Allow me to impart some wisdom upon you.",
    "In your journey ahead, you'll find peril at every turn. Monsters lurk in the shadows, waiting to strike.",
    "That sword at your side... it's more than just a weapon. It's a symbol of your courage, your resolve.",
    "Remember, when faced with danger, don't hesitate to wield it. Press the space key with conviction, and you shall prevail.",
    "But a sword alone won't guarantee your safety. No, you'll need more than that.",
    "Behold, this shield! Crafted by the finest blacksmith in the realm, it shall deflect even the deadliest of blows.",
    "To utilize its protective embrace, simply press and hold the shift key. With it, you'll become an impregnable bastion of defense.",
    "Now, young warrior, listen closely to the plea of a desperate father. My son, abducted by vile fiends, languishes in a dungeon to the west.",
    "I beseech you, rescue him from his captors! Bring him back to me, safe and sound, and you shall be richly rewarded.",
    "Gold and jewels? Of course! But more importantly, you shall earn the gratitude of a father whose heart aches with worry.",
    "Go forth, brave adventurer! Your destiny awaits, and the fate of my son hangs in the balance.",
    "Oh, and before you venture too far, allow me to mention a curious tent near the village's edge.",
    "Within it dwells a peculiar frog-merchant. He peddles potent healing potions, brewed from the essence of rare herbs.",
    "These elixirs can mend even the gravest of wounds, but they come at a cost. Golden coins, gathered from the lifeless husks of the monsters you vanquish, are his currency.",
    "Should you find yourself in dire need of healing, pay him a visit. His wares may just save your life.",
  ],
  ["Go forth, brave adventurer! Your destiny awaits, and the fate of my son hangs in the balance."],
  [
    "Allow me to remind you about the tent near the village's edge.",
    "Within it dwells a peculiar frog-merchant. He peddles potent healing potions, brewed from the essence of rare herbs.",
    "These elixirs can mend even the gravest of wounds, but they come at a cost. Golden coins, gathered from the lifeless husks of the monsters you vanquish, are his currency.",
    "Should you find yourself in dire need of healing, pay him a visit. His wares may just save your life.",
  ],
  [
    "Ah, back so soon? It seems the trials of the dungeon have not daunted your spirit.",
    "But beware, my friend. The deeper you delve into darkness, the greater the challenges you'll face.",
    "Do not let complacency be your downfall. Remember the lessons I've imparted upon you.",
    "Your sword, your shield... these are your tools, your companions in the fight against evil.",
    "And do not forget, in the heat of battle, the importance of strategy. A well-timed strike, a well-placed block... these can turn the tide in your favor.",
    "Now, go forth once more! The fate of my son, and perhaps the fate of our realm, rests in your hands.",
    "Ah, one more thing. Should you require provisions for your journey, do not overlook the frog-merchant's tent.",
    "His healing potions could mean the difference between victory and defeat.",
  ],
  [
    "You return, weary and worn. But fear not, for you have proven yourself a true hero.",
    "My son is safe, thanks to your bravery and skill.",
    "Accept this humble token of my gratitude, a reward befitting your valor.",
    "And know this, young adventurer: your deeds shall be celebrated throughout the land.",
    "The tale of your courage shall inspire generations yet unborn.",
    "But do not let fame and fortune dull your edge. The journey of a hero is never truly over.",
    "There are always new challenges to face, new evils to vanquish.",
    "Remember the lessons you've learned, the friends you've made, and the sacrifices you've endured.",
    "For in the annals of history, your name shall be written in letters of gold.",
    "Farewell, brave soul. May your adventures be many, and your heart ever steadfast.",
    "And should you ever find yourself in need of replenishment, do not forget the frog-merchant's tent. His potions are as potent as ever, ready to aid you in your quests.",
  ],
];

export const oldmanLines: { [key in Locale]: string[][] } = {
  english,
  ukrainian,
};
