export const tags = {
  player: "player",
  slime: "slime",
  doorEntrance: "door-entrance",
  shopEntrance: "shop-entrance",
  doorExit: "door-exit",
  oldman: "oldman",
  trader: "oldman",
  swordHitBox: "sword-hit-box",
  coin: "coin",
  heartsContainer: "hearts-container",
  coinsContainer: "coins-container",
  enemy: "enemy",
  dungeonEnterance: "dungeon-door-entrance",
  bossExit: "boss-exit",
  bossEnterance: "boss-entrance",
  puzzleExit: "puzzle-exit",
  puzzleEnterance: "puzzle-entrance",
  pressButton: "press-button",
  box: "box",
  prisonDoor: "prison-door",
  son: "son",
};
